[package]
edition = "2021"
name = "resistor-color"
version = "1.0.0"

[dependencies]
int-enum = "0.4.0" # https://crates.io/crates/int-enum
enum-iterator = "0.7.0" # https://crates.io/crates/enum-iterator
